version: '3.8'

services:
  web:
    build: ./
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - db
    links:
      - db:db
    networks:
      - djangonetwork
  db:
    container_name: db
    networks:
      - djangonetwork

    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./words_db.sql:/words_db.sql
    environment:
      - POSTGRES_USER=macbookpro
      - POSTGRES_DB=postgre
volumes:
  postgres_data:

networks:
  djangonetwork:
      driver: bridge