# Generated by Django 4.2.4 on 2023-08-08 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RateLimiter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=16)),
                ('country_code', models.CharField(default=None, max_length=3)),
                ('counter', models.IntegerField(default=0)),
                ('last_request_timestamp', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=20)),
                ('value', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=20)),
                ('frequency', models.IntegerField(default=0)),
                ('type', models.CharField(max_length=10)),
                ('language', models.CharField(default='en', max_length=2)),
                ('is_common', models.BooleanField(default=False)),
                ('n_of_times', models.IntegerField(default=0)),
            ],
        ),
    ]
