# Generated by Django 4.2.4 on 2023-08-08 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('words_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Statistics',
            new_name='Statistic',
        ),
    ]
