# Generated by Django 4.2.4 on 2023-08-08 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words_api', '0002_rename_statistics_statistic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='type',
            field=models.CharField(default=None, max_length=10),
        ),
    ]
