# Generated by Django 4.2.4 on 2023-08-09 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words_api', '0005_remove_word_id_alter_word_word'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='length',
            field=models.IntegerField(default=0),
        ),
    ]
